@startuml Mushrooom Thread States
hide empty description

[*] --> Alive

state Alive {
    state Sprout
    state Grown

    [*] -> Sprout
    Sprout -> Sprout: grow() / turnsToGrow--
    Sprout -down-> Grown: [turnsToGrow == 0]
}

state Dead

Alive -> Alive: decreaseTurnsToDie() / turnsToDie--
Alive -down-> Dead: dieIfUnconnected() 

Dead -> [*]


@enduml