@startuml Mushroom Body Statechart
hide empty description


state Alive {

	state NewMushroomBody
	state NormalMushroomBody
	state AdvancedMushroomBody

	[*] -> NewMushroomBody
	NewMushroomBody -down-> NormalMushroomBody : [age >= normalAge]
	NormalMushroomBody -down-> AdvancedMushroomBody : [age >= advancedAge]

}

state Dead

[*] -> Alive
Alive -> Alive: distibuteSpore() / sporesRemaining--;
Alive -down-> Dead: [sporesRemaining <= 0]

Dead -> [*]

@enduml