@startuml Mushroom Body Statechart
hide empty description

state NewMushroomBody
state NormalMushroomBody
state AdvancedMushroomBody

[*] -> NewMushroomBody
NewMushroomBody -down-> NormalMushroomBody : [age >= normalAge]
NormalMushroomBody -down-> AdvancedMushroomBody : [age >= advancedAge]
AdvancedMushroomBody -> [*]

@enduml