@startuml hasMoreActionsMycologist

participant "p: Player" as p
participant "m: Mushroom" as m

-> p : hasMoreActions()
activate p
    
p -> m : getActions()
activate m

p <-- m : actions
deactivate m

alt no actions
    <-- p : false
end

<-- p : true
deactivate p

@enduml