@startuml Mycologist.onEndOfTheRound

participant "myc: Mycologist" as myc
participant "myc.mushroom: Mushroom" as m

-> myc: onEndOfTheRound()
activate myc

myc -> m: onEndOfTheRound()
activate m

loop for each thread
	create participant Thread
	m -> Thread: isConnectedToBody()
	activate Thread
	m <-- Thread: result

	alt is not connected to body
		m -> Thread: decreaseTurnsToDie()
		m <-- Thread
	else
		m -> Thread: resetTurnsToDie()
		m <-- Thread

		m -> Thread: grow()
		m <-- Thread
	end

	m -> Thread: dieIfUnconnected()
	m <-- Thread
	deactivate Thread
end

m -> m: refreshActionPoints()
activate m

m --> m
deactivate m

myc <-- m
deactivate m

<-- myc
deactivate myc

@enduml