@startuml endofround_tecton

participant "t: Tecton" as tecton

-> tecton: onEndOfTheRound()
activate tecton

opt random generated number lower than splitchance
	tecton -> tecton: split()
	activate tecton

	tecton --> tecton
	deactivate tecton
end

<-- tecton
deactivate tecton
@enduml
