@startuml split_sequence
title Tecton.split

participant "g: Game" as game
participant "t: Tecton" as tecton
participant "nt: New Tecton" as newtecton
participant "mt: Mushroom Thread" as thread

game -> tecton: split()
activate game
activate tecton

tecton --> newtecton: Instantiate
activate newtecton
deactivate newtecton

loop for each MushroomThread in mushroomThreads[]

tecton -> thread: cut()
activate thread

thread --> tecton
deactivate thread

end

game <-- tecton
deactivate tecton
deactivate game

@enduml