@startuml split_sequence
title Tecton.split

participant "t: Tecton" as tecton
participant "nt: New Tecton" as newtecton
participant "mt: Mushroom Thread" as thread
collections "mushroomThreads: MushroomThread[]" as mts

-> tecton: split()
note right: hívó fél: Tecton.onEndOfTheRound\nvagy ThreadKillingTecton.onEndOfTheRound
activate tecton

opt random generated number lower than splitChance

tecton -> newtecton: Instantiate
activate newtecton

tecton <-- newtecton
deactivate newtecton

loop for each MushroomThread in mushroomThreads[]

	tecton -> thread: cut()
	note right: lásd: MushroomThread.cut diagram
	activate thread

	thread --> tecton
	deactivate thread

end

<-- tecton
deactivate tecton

@enduml