@startuml performAction

participant "p: Player" as p
participant "i: Interactable" as i
participant "a: Action" as a

-> p : performAction(i, a)
activate p

p -> i : do(a)
activate i

i -> a : perform()
activate a

a --> i
deactivate a

i --> p
deactivate i

<-- p
deactivate p

@enduml