' Test-casek:
' - Tecton Grow Body Body Fail: t1-en van mt1; t1-en van s1_1, s1_2, s1_3; t1-en van mb1
'   - t1-re próbálunk új gombatestet növeszteni, ami nem sikerül, mert már van ott egy (mb1)
'   - MÓDOSULT: t4-ből t1; mb4-ből mb1 ~Tmas

@startuml communicationTecton3_4

title Tecton Grow Body Body Fail\n(all requirements are met, but there is a MushroomBody on t1 already)

actor "Tester" as ts
participant "t1: Tecton" as t1

participant "mt1: MushroomThread" as mt1

participant "s1_1: Spore" as s1_1
participant "s1_2: Spore" as s1_2
participant "s1_3: Spore" as s1_3

participant "mb1: MushroomBody" as mb1

activate ts

ts -> t1: 1 -> Initialize()
activate t1

ts <-- t1
deactivate t1

ts -> mt1: 3 -> Initialize(t1)
activate mt1
	' tecton beállítás
	' growOnTecton() blackboxolja, hogy a Tecton MushroomThreadjei közé is felveszi magát
	mt1 -> mt1: 3.1 -> growOnTecton(t1)

ts <-- mt1
deactivate mt1

' ------------------------------------------
' s1_1: t1-en
ts -> s1_1: 4 -> Initialize(t2)
activate s1_1

' sporeTecton blackboxolja, hogy a Tectonon hozzáadja magát a MushroomSporeok közé
s1_1 -> s1_1: 4.1 -> sporeTecton(t2)

ts <-- s1_1
deactivate s1_1


' ------------------------------------------
' s1_2: t1-en
ts -> s1_2: 5 -> Initialize(t2)
activate s1_2

' sporeTecton blackboxolja, hogy a Tectonon hozzáadja magát a MushroomSporeok közé
s1_2 -> s1_2: 5.1 -> sporeTecton(t2)

ts <-- s1_2
deactivate s1_2


' ------------------------------------------
' s1_3: t1-en
ts -> s1_3: 6 -> Initialize(t2)
activate s1_3

' sporeTecton blackboxolja, hogy a Tectonon hozzáadja magát a MushroomSporeok közé
s1_3 -> s1_3: 6.1 -> sporeTecton(t2)

ts <-- s1_3
deactivate s1_3


' ------------------------------------------
' mb1: 
' - t1-en nő
ts -> mb1: 3.1 -> Initialize(t1)
activate mb1

' a growOnTecton() blackboxolja, hogy a Tectonon regisztrálja magát, mint MushroomBody
mb1 -> mb1: 3.1.1 growOnTecton(t1)

ts <-- mb1
deactivate mb1


deactivate ts

@enduml