' TODO:
@startuml Grow Body
title MushroomBody.growBody

actor "Mycologist" as mycologist
participant "mb: MushroomBody" as mb
participant "t: Tecton" as t

activate mycologist

mycologist --> mb: Initialize
activate mb

mb -> t: hasBody()
activate t
t --> mb: hasBody: boolean
deactivate t

    opt hasBody == false
        mb -> t: getSporeCount()
        activate t
        t --> mb: sporeCount: int
        deactivate t
        
        opt sporeCount > mb.sporesNeeded
            mb -> t: hasThreadFromMushroom(m)
            activate t
            t --> mb: hasthreadFromMushroom: boolean
            deactivate t

            opt hasThreadFromMushroom
                mb -> t: setBody(mb)
                activate t
                t --> mb
                deactivate t
                deactivate mb
            end
        end
    end

deactivate mycologist

@enduml