@startuml Insectologist.moveToTecton

title Insect.moveToTecton

actor "Insectologist" as ins
participant "insect: Insect" as i
participant "insect.tecton: Tecton" as it
participant "t: Tecton" as t

ins -> i: moveToTecton(t)
activate ins
activate i

i -> it: isNeighbour(t)
activate it

i <-- it: isNeighbour
deactivate it

i -> it: verifyConnection(t)
activate it

i <-- it: isConnected
deactivate it

alt isNeighbour && isConnected && canMove

	i -> it: unregisterInsect(i)
	activate it

	i <-- it
	deactivate it

	i -> t: registerInsect(i)
	activate t

	i <-- t
	deactivate t

	ins <-- i
else
	ins <-- i: Exception
end

deactivate i

deactivate ins

@enduml