@startuml Effect tests
left to right direction

actor "Tester" as t

rectangle "Effect Tests" {
    usecase "stunEffect test\n(bénító effekt hatása)" as test1
    usecase "speedEffect test\n(gyorsító effekt hatása)" as test2
    usecase "slowEffect test\n(lassító effekt hatása)" as test3
}

t -- test1
t -- test2
t -- test3

@enduml