@startuml blockEffect

title blockEffect test

Actor Tester as test
activate test
test -> tester: testBlockEffect()

participant "Skeleton" as tester

participant "blockEffect: BlockEffect" as speed
participant "i: Insect" as insect

activate tester

tester -> speed: applyEffect(i)
activate speed

speed->insect:setCounter()
activate insect

speed<--insect

speed->insect:setCanCut()
speed<--insect
deactivate insect

speed --> tester
deactivate speed

tester -> insect: getCanCute()
activate insect

insect -->tester:false


tester -> insect: getTimerIsNull()

insect -->tester:false


test<-- tester
deactivate tester

@enduml