@startuml blockEffect

title blockEffect test

Actor Tester as test
participant "Skeleton" as tester

participant "blockEffect: BlockEffect" as speed
participant "i: Insect" as insect

activate test

test -> tester: testBlockEffect()
activate tester

tester -> speed: applyEffect(i)
activate speed

speed->insect:setCounter()
activate insect

speed<--insect
deactivate insect

speed->insect:setCanCut()
activate insect

speed<--insect
deactivate insect

speed --> tester
deactivate speed

tester -> insect: getCanCut()
activate insect

insect -->tester:false
deactivate insect

tester -> insect: isCounterSet()

activate insect
insect -->tester:false
deactivate insect

test<-- tester
deactivate tester

@enduml