@startuml slowEffect

title slowEffect test


Actor Tester as test
activate test
test -> tester: testBlockEffect()

participant "Skeleton" as tester

participant "slowEffect: SlowEffect" as slow
participant "i: Insect" as insect

activate tester

tester -> slow: applyEffect(i)
activate slow

slow --> tester
deactivate slow


test<-- tester
deactivate tester
@enduml