@startuml speedEffect

title speedEffect test

Actor Tester as test
participant "Skeleton" as tester

participant "speedEffect: SpeedEffect" as speed
participant "i: Insect" as insect

activate test
test -> tester: testBlockEffect()



activate tester

tester -> speed: applyEffect(i)
activate speed

speed --> tester
deactivate speed


test<-- tester
deactivate tester
@enduml