@startuml stunEffect

title stunEffect test

Actor Tester as test
activate test
test -> tester: testBlockEffect()

participant "Skeleton" as tester

participant "stunEffect: StunEffect" as speed
participant "i: Insect" as insect

activate tester

tester -> speed: applyEffect(i)
activate speed

speed->insect: exhaustActions()
activate insect

speed<--insect

speed->insect:setCanMove()
speed<--insect
deactivate insect

speed --> tester
deactivate speed

tester -> insect: getCanMove()
activate insect


insect --> tester: false


test<-- tester
deactivate tester
@enduml