@startuml createConnectionMVC

title createConnection
actor "Mycologist" as mc
participant "action: CreateConnectionAction" as act
participant "controller: GameController" as ctr
participant "mt: MushroomThread" as mt

mc -> act: actionPerformed()
activate mc

activate act

act -> ctr: getSelectedThread()
activate ctr
act <-- ctr: mt: MushroomThread
act -> ctr:  getSelectedTecton()
act <-- ctr: t: Tecton
deactivate ctr

act -> mt: createConnection(t)
activate mt

act <-- mt
deactivate mt

mc <-- act
deactivate act

deactivate mc

@enduml