@startuml CutThreadAction.perform

participant "action: CutThreadAction" as mi_action
participant "action.i: Insect" as insect

-> mi_action: perform()
activate mi_action

mi_action -> insect: cutMushroomThread(action.thread)
activate insect

mi_action <-- insect
deactivate insect

<-- mi_action
deactivate mi_action

@enduml