@startuml CutThreadAction.perform

actor "insectologist: Insectologist" as insectologist
participant "action: CutThreadAction" as mi_action
participant "action.i: Insect" as insect
participant "action.thread: MushroomThread"

insectologist -> mi_action: perform()
activate insectologist
activate mi_action

mi_action -> insect: cutMushroomThread(action.thread)
activate insect
note right: Insect.cutMushroomThread()

mi_action <-- insect
deactivate insect

insectologist <-- mi_action
deactivate mi_action
deactivate insectologist

@enduml