@startuml Distribute Spore Action
actor "mycologist: Mycologist" as mycologist 
participant "dsa: DistributeSporeAction" as dsa
participant "dsa.body: MushroomBody" as mb

mycologist -> dsa: perform()
activate mycologist
activate dsa

dsa -> mb: distibuteSpore()
activate mb

note right: Mushroom.distributeSpore()

mb --> dsa 
deactivate mb

mycologist <-- dsa
deactivate dsa
deactivate mycologist


@enduml
