@startuml Grow Body Action
actor "mycologist: Mycologist" as mycologist
participant "gba: GrowBodyAction" as gba
participant "gba.mushroom: Mushroom" as m
participant "gba.tecton: Tecton" as t

mycologist -> gba: perform()
activate mycologist
activate gba

gba -> m: growBody(gba.tecton)
activate m
note right: MushroomBody.growBody()

m --> gba
deactivate m

mycologist <-- gba
deactivate gba
deactivate mycologist

@enduml