@startuml Grow Thread Action
actor "mycologist: Mycologist" as mycologist
participant "gta: GrowThreadAction" as gta
participant "gta.thread: MushroomThread" as mt
participant "gta.tecton: Tecton" as t

mycologist -> gta: perform()
activate mycologist
activate gta

gta -> mt: createConnection(gta.tecton)
activate mt
note right: MushroomThread.createConnection()

mt --> gta
deactivate mt

mycologist <-- gta
deactivate gta
deactivate mycologist

@enduml