@startuml MoveInsectAction.perform
title MoveInsectAction.perform

actor "insectologist: Insectologist" as insectologist
participant "action: MoveInsectAction" as mi_action
participant "action.i: Insect" as insect
participant "action.to: Tecton" as t

insectologist -> mi_action: perform()
activate insectologist
activate mi_action

mi_action -> insect: moveToTecton(action.to)
activate insect
note right: Insect.moveToTecton(action.to)

mi_action <-- insect
deactivate insect

insectologist <-- mi_action
deactivate mi_action
deactivate insectologist

@enduml