@startuml InfertileTectonGrowBodyTest

title InfertileTecton Grow Body

actor "Tester" as ts
participant "t: InfertileTecton" as t
participant "newMb: MushroomBody" as newMb
participant "l: Logger" as l

activate ts

ts -> l: printState(t)
activate l
ts <-- l
deactivate l

ts -> newMb: Instantiate()
activate newMb
ts <-- newMb
deactivate newMb

ts -> t: setBody(newMb)
activate t

ts <-- t: throw Exception
deactivate t

alt caught Exception
    ts -> l: log("InfertileTecton can't grow a body")
    activate l
    ts <-- l
    deactivate l
end

ts -> l: printState(t)
activate l
ts <-- l
deactivate l

deactivate ts

@enduml