@startuml Mushroom boy Last Spore

actor "Tester" as tester
participant "body: MushroomBody" as body
participant "body.tecton: Tecton" as tecton

tester -> body: distributeSpores()
activate tester
activate body

body -> body: remainingSpores--;
activate body
body--> body
deactivate body 

body -> tecton: removeBody(body)
activate tecton
tecton --> body
deactivate tecton


body --> tester
deactivate body
deactivate tester

@enduml