@startuml tectonGrowThreadTest

title SingleThreadTecton Grow Body (Success/Fail)

actor "Tester" as tst
participant "t1: SingleThreadTecton" as t1
participant "mt: MushroomThread" as mt
participant "l: Logger" as l

activate tst

tst -> l: printState(t1)
activate l
tst <-- l
deactivate l

tst -> t1: addConnection(mt)
activate t1

alt t1.mushroomThreads.Count >= 1
    tst <-- t1: throw Exception

    alt caught Exception
        tst -> l: printError("SingleThreadTecton can't have more than one MushroomThread")
        activate l
        tst <-- l
        deactivate l    
    end
end

alt not mt.isConnectingTecton(t1) 
    tst <-- t1: throw Exception

    alt caught Exception
        tst -> l: printError("Tectons are not neighbours")
        activate l
        tst <-- l
        deactivate l    
    end
end

t1 -> t1: addConnection(mt)
tst <-- t1
deactivate t1

tst -> l: printState(t1)
activate l
tst <-- l
deactivate l

deactivate tst

@enduml