@startuml tectonGrowThreadTest

title SingleThreadTecton Grow Thread Success

actor "Tester" as tst
participant "t2: SingleThreadTecton" as t2
participant "newMt: MushroomThread" as newMt
participant "l: Logger" as l

activate tst

tst -> l: printState(t2)
activate l
tst <-- l
deactivate l

tst -> newMt: Instantiate()
activate newMt
tst <-- newMt
deactivate newMt

tst -> t2: addConnection(newMt)
activate t2

tst <-- t2
deactivate t2

tst -> l: printState(t2)
activate l
tst <-- l
deactivate l

deactivate tst

@enduml