@startuml speedEffect

actor Tester as tester

participant "Logger" as logger
participant "speedEffect: SpeedEffect" as speed
participant "i: Insect" as insect

activate tester

tester -> speed: applyEffect(i)
activate speed

speed --> tester
deactivate speed

tester -> logger: log("speed effect test, speedEffect, i")
note right: Az effektet a kontroller kezeli, az insect visszakapta az összes lépését
activate logger

logger--> tester
deactivate logger

deactivate tester

@enduml