@startuml tectonGrowBodyTest

title Tecton Grow Body Thread Fail

actor "Tester" as ts
participant "t2: Tecton" as t2
participant "newMb: MushroomBody" as newMb
participant "l: Logger" as l

activate ts

ts -> l: printState(t2)
activate l
ts <-- l
deactivate l

ts -> newMb: Instantiate()
activate newMb
ts <-- newMb
deactivate newMb

ts -> t2: setBody(newMb)
activate t2

ts <-- t2: throw Exception
deactivate t2

alt caught Exception
    ts -> l: log("Tecton needs MushroomThread from MushroomBody before growing it")
    activate l
    ts <-- l
    deactivate l    
end

ts -> l: printState(t2)
activate l
ts <-- l
deactivate l

deactivate ts

@enduml