@startuml tectoGrowBodyTest

actor "Tester" as ts
participant "t: Tecton" as t
participant "mb: MushroomBody" as mb

activate ts

ts -> t: setBody(mb)
activate t

alt t.hasBody
    ts <-- t: throw Exception
end

alt not t.hasThreadFrom(mb)
    ts <-- t: throw Exception
end

alt t.spores.Count < 3
    ts <-- t: throw Exception
end

t -> t: t.mushroomBodies.Add(mb)

ts <-- t
deactivate t

deactivate ts

@enduml