@startuml tectonSplitTest

title Tecton Split

actor "Tester" as tst
participant "t: Tecton" as t
participant "newTec: Tecton" as ntec
participant "l: Logger" as l

activate tst

tst -> l: printState(t)
activate l
tst <-- l
deactivate l

tst -> t: split()
activate t

' ez nemtom így mennyire jó, de nincs jobb ötletem és leszarom XD
t -> ntec: Instantiate([t, t.getNeighbours()])
activate ntec

t <-- ntec:
deactivate ntec

tst <-- t:
deactivate t

tst -> l: printState(newTec)
activate l
tst <-- l
deactivate l

tst -> l: printState(t)
activate l
tst <-- l
deactivate l

deactivate tst

@enduml