@startuml tectonKillThreadTest

title Tecton Kill Thread

actor "Tester" as tst
participant "t: Tecton" as t
participant "l: Logger" as l

activate tst

tst -> l: printState(t)
activate l
tst <-- l
deactivate l

tst -> t: killThread(mt)
activate t

tst <-- t: throw Exception
deactivate t

alt caught Exception
        tst -> l: log("Non-ThreadKillingTecton can't kill MushroomThread")
        activate l
        tst <-- l
        deactivate l    
    end

tst -> l: printState(t)
activate l
tst <-- l
deactivate l

deactivate tst

@enduml