@startuml tectonGrowBodyTest

title Tecton Grow Body Spore Fail

actor "Tester" as ts
participant "t1: Tecton" as t1
participant "newMb: MushroomBody" as newMb
participant "l: Logger" as l

activate ts

ts -> l: printState(t1)
activate l
ts <-- l
deactivate l

ts -> newMb: Instantiate()
activate newMb
ts <-- newMb
deactivate newMb

ts -> t1: setBody(newMb)
activate t1

ts <-- t1: throw Exception
deactivate t1

alt caught Exception
    ts -> l: log("Tecton needs at least 3 Spores to grow a MushroomBody")
    activate l
    ts <-- l
    deactivate l    
end

ts -> l: printState(t1)
activate l
ts <-- l
deactivate l

deactivate ts

@enduml