@startuml tectonSplitTest

title Tecton Split

actor "Tester" as tst
participant "tec: Tecton" as tec
participant "newTec: Tecton" as ntec
participant "l: Logger" as l

activate tst

tst -> l: printState(tec)
activate l
tst <-- l
deactivate l

tst -> tec: split()
activate tec

' ez nemtom így mennyire jó, de nincs jobb ötletem és leszarom XD
tec -> ntec: Instantiate([tec, tec.getNeighbours()])
activate ntec

tec <-- ntec:
deactivate ntec

tst <-- tec:
deactivate tec

tst -> l: printState(newTec)
activate l
tst <-- l
deactivate l

tst -> l: printState(tec)
activate l
tst <-- l
deactivate l

deactivate tst

@enduml