@startuml tectonGrowBodyTest

title Tecton Grow Body Thread Fail

actor "Tester" as ts
participant "t: Tecton" as t
participant "mb: MushroomBody" as mb
participant "l: Logger" as l

activate ts

ts -> l: printState(t)
activate l
ts <-- l
deactivate l

ts -> t: setBody(mb)
activate t

ts <-- t: throw Exception
deactivate t

alt caught Exception
    ts -> l: log("Tecton needs MushroomThread from MushroomBody before growing it")
    activate l
    ts <-- l
    deactivate l    
end

ts -> l: printState(t)
activate l
ts <-- l
deactivate l

deactivate ts

@enduml