@startuml tectonGrowBodyTest

title Tecton Grow Body Success

actor "Tester" as ts
participant "s: Skeleton" as s
participant "t1: Tecton" as t1
participant "newMb: MushroomBody" as newMb

activate ts

ts -> s: TectonGrowBodySuccess()
activate s

s -> newMb: Instantiate()
activate newMb
s <-- newMb
deactivate newMb

s -> t1: setBody(newMb)
activate t1

t1 -> t1: mushroomBody = newMb

s <-- t1
deactivate t1

ts <-- s
deactivate s

deactivate ts

@enduml