@startuml tectonGrowThreadTest

title Tecton Grow Thread (Success/Fail)

actor "Tester" as tst
participant "t: Tecton" as t
participant "mt: MushroomThread" as mt
participant "l: Logger" as l

activate tst

tst -> l: printState(t)
activate l
tst <-- l
deactivate l

tst -> t: addConnection(mt)
activate t

tst <-- t: throw Exception
deactivate t

alt caught Exception
    tst -> l: log("Can't connect non-neighbour Tectons with MushroomThread")
    activate l
    tst <-- l
    deactivate l    
end

tst -> l: printState(t)
activate l
tst <-- l
deactivate l

deactivate tst

@enduml