@startuml threadKillingTectonKillThreadTest

title ThreadKillingTecton Kill Thread

actor "Tester" as tst
participant "t: ThreadKillingTecton" as t
participant "mt: MushroomThread" as mt
participant "ct: MushroomThread" as ct
participant "l: Logger" as l

activate tst

tst -> l: printState(t)
activate l
tst <-- l
deactivate l

tst -> t: killThread(mt)
activate t

t -> mt: cut()
activate mt

loop ct in connectedThreads
    mt -> ct: removeConnectedThread(mt)
    activate ct

    mt <-- ct
    deactivate ct
end

t <-- mt
deactivate mt

t -> t: removeConnection(mt)

tst <-- t
deactivate t

tst -> l: printState(t)
activate l
tst <-- l
deactivate l

deactivate tst

@enduml