@startuml Advanced Mushroom Body Distribute Spores

title Advanced Mushroom Body Distribute Spores

actor "Tester" as tester

participant "Skeleton" as skeleton

participant "advancedBody: MushroomBody" as amb

participant "t1: Tecton" as t1

activate tester

collections "tectonsToSpore: Tecton[0..*]" as tectons
collections "neighbours: Tecton [0..*]"
participant "t2: Tecton" as t2
participant "t3: Tecton" as t3

participant "s1: Spore" as s1
participant "s2: Spore" as s2
participant "s3: Spore" as s3

tester -> skeleton: testAdvancedMushroomDistributeSpores()
activate skeleton

skeleton -> amb: distributeSpores() 
activate amb

' COPY BEGIN

amb -> t1 : getNeighbours()

activate t1
t1 --> amb : neighbours: Tecton[0..*]
note right: neighbours == {t2} 
deactivate t1

amb --> tectons: Instantiate
note right: belso lista
activate tectons
deactivate tectons

amb -> tectons: add(advancedMushroomBody.tecton) 
note right: itt advancedMushroomBody.tecton == t1
activate tectons
tectons --> amb
deactivate tectons

amb -> tectons: addAll(neighbours);
activate tectons
tectons --> amb
deactivate tectons

    ' Could not use
    ' opt body.age >= advancedAge
    '     loop for each neighbour in neighbours
    '         opt !tectonsToSpore.contains(neighbour)
    '             body -> tectons: tectonsToSpore.add(neighbourOfNeighbour)
    '             activate tectons
    '             tectons --> body
    '             deactivate tectons
    '         end
    '     end
    ' end

amb -> tectons: add(t3)
activate tectons
tectons --> amb
deactivate tectons

    ' Could not use
    ' loop for each tectonToSpore in tectonsToSpore
    ' amb -> tectons : addSpore(spore: Spore)
    ' activate tectons
    ' tectons --> amb 
    ' deactivate tectons
    ' end

amb --> s1: Instantiate
activate s1
deactivate s1

amb --> t1: addSpore(s1: Spore)
activate t1
t1 --> amb
deactivate t1

amb --> s2: Instantiate
activate s2
deactivate s2

amb --> t2: addSpore(s2: Spore)
activate t2
t2 --> amb
deactivate t2

amb --> s3: Instantiate
activate s3
deactivate s3

amb --> t3: addSpore(s3: Spore)
activate t3
t3 --> amb
deactivate t3


    ' Not part of the test-case
    ' opt body.remainingSpore == 0
    '     body -> tecton : removeBody(body)
    '     activate tecton
    '     tecton --> body
    '     deactivate tecton
    ' end
' COPY END

amb --> skeleton
deactivate amb

skeleton --> tester
deactivate skeleton

@enduml