@startuml Mushroom Thread Is Traversible Fail Cut

title Mushroom Thread Is Connecting Fail Cut

actor "Tester" as tester
participant "Skeleton" as skeleton

participant "mt1: MushroomThread" as mt1
participant "mt2: MushroomThread" as mt2

participant "mt2.tecton: Tecton" as t2

activate tester

tester -> skeleton: test_connectingTectonFailCut()
activate skeleton

skeleton -> mt1: isConnectingTecton(mt2.tecton)
activate mt1

mt1 -> mt2: getCutState()
activate mt2
mt2 --> mt1: CutState.UNCUT
deactivate mt2

mt1 -> mt2: getGrowState()
activate mt2
mt2 --> mt1: GrowState.GROWN
deactivate mt2

mt1 -> mt1: getGrowState()
activate mt1
mt1 --> mt1: GrowState.GROWN
deactivate mt1


mt1 -> mt1: getCutState()
activate mt1
mt1 --> mt1: CutState.CUT
deactivate mt1

mt1 --> skeleton: false
deactivate mt1

skeleton --> tester
deactivate skeleton

@enduml