@startuml Create Connection To Non Neighbouring Tecton

title Create Connection To Non Neighbouring Tecton

actor "Tester" as tester

participant "mt: MushroomThread" as mt
participant "tecton: Tecton" as not_negihbour
participant "Logger" as logger

activate tester

tester -> mt: createConnection(tecton)
activate mt
mt --> tester: exception
deactivate mt

tester -> logger: printError("Tectons are not neighbours") 
deactivate tester


@enduml