@startuml Mushroom Thread Evolve

title Mushroom Thread Evolve

actor "Tester" as tester
participant "Skeleton" as skeleton

participant "evolvingThread: MushroomThread" as emt

activate tester
tester -> skeleton: test_threadEvolve()
activate skeleton

skeleton -> emt: onEndOfTheRound()
activate emt

emt -> emt: isConnectedToBody()
activate emt
note right: lásd: MushroomThread.isConnectedToBody() sd 
emt --> emt: true
deactivate emt

emt -> emt: turnsToGrow--
activate emt
emt --> emt
deactivate emt

emt --> skeleton
deactivate emt

skeleton --> tester
deactivate skeleton

@enduml