@startuml Mushroom Thread Die

title Mushroom Thread Die

actor "Tester" as tester
participant "dyingThread: MushroomThread" as dymt
participant "t2: Tecton" as t2
participant "Logger" as logger


activate tester

tester -> t2: hasThreadFromMushroom(dyingThread)
activate t2
t2 --> tester: true
deactivate t2

tester -> logger: print(true, hasThreadFromMushroom)
activate logger
logger --> tester
deactivate logger

tester -> dymt: onEndOfTheRound() 
activate dymt
dymt --> tester
deactivate dymt

tester -> logger: print("void", onEndOfTheRound)
activate logger
logger --> tester
deactivate logger

tester -> t2: hasThreadFromMushroom(dyingThread)
activate t2
t2 --> tester: false
deactivate t2

tester -> logger: print(false, hasThreadFromMushroom)
activate logger
logger --> tester
deactivate logger

deactivate tester

@enduml