@startuml Mushroom Thread Die

title Mushroom Thread Die

actor "Tester" as tester
participant "Skeleton" as skeleton

participant "dyingThread: MushroomThread" as dymt
participant "t2: Tecton" as t2

activate tester 

tester -> skeleton: test_threadDie()
activate skeleton

skeleton -> dymt: onEndOfTheRound()
activate dymt

dymt -> dymt: isConnectedToBody()
activate dymt
note right: lásd: MushroomThread.isConnectingToBody() sd 
dymt --> dymt: false
deactivate dymt


dymt -> dymt: turnsToDie--
activate dymt
dymt --> dymt
deactivate dymt

dymt -> dymt: dieIfUnconnected()
activate dymt

dymt -> t2: removeConnection(dyingThread)
activate t2
t2 --> dymt
deactivate t2

dymt --> dymt
deactivate dymt
note right: Ha lenne fonál, a connectedThreads listájában,\n akkor azokon végig futna és meghívá rajtuk a\n "removeConnection(dyingThread)"-et

dymt --> skeleton
deactivate dymt

skeleton --> tester
deactivate skeleton


@enduml