@startuml Mushroom Thread Dissolve

title Mushroom Thread Dissolve

actor "Tester" as tester
participant "Skeleton" as skeleton

participant "dissolvingThread: MushroomThread" as dimt

activate tester 

tester -> skeleton: test_threadDissolve()
activate skeleton

skeleton -> dimt: onEndOfTheRound()
activate dimt

dimt -> dimt: isConnectedToBody()
activate dimt
note right: lásd: MushroomThread.isConnectedToBody() sd 
dimt --> dimt: false
deactivate dimt

dimt -> dimt: turnsToDie--
activate dimt
dimt --> dimt
deactivate dimt

dimt -> dimt: dieIfUnconnected()
activate dimt
dimt --> dimt
deactivate dimt

dimt --> skeleton
deactivate dimt

skeleton --> tester
deactivate skeleton


@enduml