@startuml Mushroom Thread Growth

title Mushroom Thread Growth

actor "Tester" as tester
participant "Skeleton" as skeleton

participant "normalThread: MushroomThread" as nmt

activate tester
tester -> skeleton: test_threadEvolve()
activate skeleton

skeleton -> nmt: onEndOfTheRound()
activate nmt

nmt -> nmt: isConnectedToBody()
activate nmt
note right: lásd: MushroomThread.isConnectingToBody() sd 
nmt --> nmt: true
deactivate nmt

nmt -> nmt: turnsToGrow--
activate nmt
nmt --> nmt
deactivate nmt

nmt -> nmt: growState = GrowState.GROWN
activate nmt
nmt --> nmt
deactivate nmt

nmt --> skeleton
deactivate nmt

skeleton --> tester
deactivate skeleton

@enduml