@startuml Thread Cut Connection Only One Body

title Thread Cut Connection Only One Body

actor "Tester" as tester

participant "mt1: MushroomThread" as mt1
participant "mt2: MushroomThread" as mt2
participant "mt3: MushroomThread" as mt3

participant "body: MushroomBody" as mb

activate tester

tester -> mt1: isConnectedToBody()
activate mt1
mt1 --> tester: true
deactivate mt1

tester -> mt2: isConnectedToBody()
activate mt2
mt2 --> tester: true
deactivate mt2

tester -> mt3: isConnectedToBody()
activate mt3
mt3 --> tester: true
deactivate mt3

tester -> mt2: cut()
activate mt2
mt2 --> tester
deactivate mt2

tester -> mt1: isConnectedToBody()
activate mt1
mt1 --> tester: false
deactivate mt1

tester -> mt2: isConnectedToBody()
activate mt2
mt2 --> tester: false
deactivate mt2

tester -> mt3: isConnectedToBody()
activate mt3
mt3 --> tester: true
deactivate mt3

@enduml