@startuml Thread Cut Connection Only One Body

title Thread Cut Connection With Only One Body

actor "Tester" as tester
participant "Skeleton" as  skeleton

participant "mt1: MushroomThread" as mt1
participant "mt2: MushroomThread" as mt2
participant "mt3: MushroomThread" as mt3

participant "mt1.tecton: Tecton" as t1
participant "mt3.tecton: Tecton" as t3

activate tester

tester -> skeleton: test_cutConnectionOneBody()
activate skeleton

' CUT
skeleton -> mt2: cut()
activate mt2
mt2 --> skeleton 
deactivate mt2

' MT1
skeleton -> mt1: isConnectedToBody()
activate mt1

mt1 -> t1: hasBody()
activate t1
t1 --> mt1: false
deactivate t1

mt1 --> skeleton: false
deactivate mt1

' MT2

skeleton -> mt2: isConnectedToBody()
activate mt2
mt2 --> skeleton: false 
note right: cutState == CUT után egyből kilép
deactivate mt2

' MT3
skeleton -> mt3: isConnectedToBody()
activate mt3

mt3 -> t3: hasBody()
activate t3
t3 --> mt3: true
deactivate t3

mt3 --> skeleton: true
deactivate mt3

skeleton --> tester
deactivate skeleton

@enduml