@startuml test_eatMushroomSpore2

title EatMushroomSpore Fail (no spore on tecton)

actor "Tesztelő" as t
participant "Skeleton" as ske
participant "insect: Insect" as i
participant "t1: Tecton" as t1

activate t

t -> ske: test_eatMushroomSpore2()
activate ske

	ske -> i: eatMushroomSpore()
	activate i
	note right: lásd: Insect.eatMushroomSpore

	
	i -> t1: getRandomSpore()
	note right: a getSporeCount() == 0\nágra futunk, kivétel
	activate t1

	i <-- t1: Exception
	deactivate t1

	ske <-- i: Exception
	deactivate i

t <-- ske
deactivate ske

deactivate t

@enduml