@startuml test_eatMushroomSpore1

title EatMushroomSpore Success

actor "Tesztelő" as t
participant "Skeleton" as ske
participant "insect: Insect" as i
participant "t1: Tecton" as t1

activate t

t -> ske: test_eatMushroomSpore1()
note right: ld. sikeres eatMushroomSpore teszt init diagram
activate ske

	ske -> i: eatMushroomSpore()
	activate i
	note right: lásd: Insect.eatMushroomSpore

	ske <-- i
	deactivate i

t <-- ske
deactivate ske

deactivate t

@enduml