@startuml moveToTectonInit

title MoveToTecton test case-k inicializációja
skinparam linestyle ortho

rectangle "Tesztelő" as tester
rectangle "t1: Tecton" as t1
rectangle "t2: Tecton" as t2
rectangle "t3: Tecton" as t3
rectangle "t4: Tecton" as t4
rectangle "ins: Insect" as ins

rectangle "mb: MushroomBody" as mb
note bottom: pillanatnyilag nincs függvény hogy a gombatest\nközvetlenül fonalat növesszen

rectangle "mt1: MushroomThread" as mt1
rectangle "mt2: MushroomThread" as mt2

tester --> t1: 1.1 → Initialize()
tester --> t2: 1.2 → Initialize()
tester --> t3: 1.3 → Initialize()
tester --> t4: 1.4 → Initialize()

tester --> t1: 2 → addNeighbour([t2, t3])
t1 --> t2: 2.1 → registerNeighbour(t1)
t1 --> t3: 2.2 → registerNeighbour(t1)

tester --> t4: 3 → addNeighbour([t3])
t4 --> t3: 3.1 → registerNeighbour(t4)

tester --> ins: 4.1 → Initialize()
tester --> ins: 4.2 → setTecton(t1)
ins --> t1: 4.2.1 → registerInsect(ins)

tester --> mb: 5 → Initialize(t1)
mb --> t1: 5.1 → setBody(mb)

tester --> mb: 6 → createConnection(t3)
mb --> mt1: 6.1 → Initialize(???)

tester --> mt1: 7 → createConnection(t4)
mt1 --> mt2: 7.1 → Initialize(???)

@enduml