@startuml test_moveToTecton4

title Move to Tecton Fail\n(while blocked)

actor "Tesztelő" as t
participant "ins: Insect" as i
participant "target: Tecton" as target
participant "logger: Logger" as logger

activate t
t -> t: test_moveToTecton4()
note right: ld. MoveToTecton teszt init diagram
activate t

	t -> logger: printState(insect)
	activate logger

	t <-- logger
	deactivate logger

	create originalTecton
	t -> originalTecton: Initialize(ins.tecton)
	activate originalTecton

	t <-- originalTecton
	deactivate originalTecton

	t -> i: moveToTecton(target)
	activate i
	note right: lásd: Insect.moveToTecton

	t <-- i
	deactivate i

	t -> logger: print("void", "moveToTecton", target)
	activate logger

	t <-- logger
	deactivate logger

	t -> logger: printState(insect)
	activate logger
	t <-- logger
	deactivate logger

	opt ins.tecton != originalTecton
		t -> logger: printError("test_moveToTecton4 failed")
		activate logger

		t <-- logger
		deactivate logger
	end

	deactivate t
deactivate t


@enduml