@startuml test_moveToTecton2

title Move to Tecton Fail\n(non-neighboring tecton)

actor "Tesztelő" as t
participant "Skeleton" as ske
participant "ins: Insect" as i
participant "t4: Tecton" as t4

activate t

t -> ske: test_moveToTecton2()
note right: ld. MoveToTecton teszt init diagram
activate ske
	ske -> i: moveToTecton(t4)
	activate i
	note right: lásd: Insect.moveToTecton

	ske <-- i
	deactivate i

'	opt ins.tecton != t1
'		t -> logger: printError("test_moveToTecton2 failed")
'		activate logger
'
'		t <-- logger
'		deactivate logger
'	end

t <-- ske
deactivate ske

deactivate t


@enduml