@startuml test_moveToTecton4

title Move to Tecton Fail\n(while stunned)

actor "Tesztelő" as t
participant "ins: Insect" as i
participant "target: Tecton" as target
participant "logger: Logger" as logger

activate t

t -> logger: printState(insect)
note right: ld. MoveToTecton (bénított eset) teszt init diagram
activate logger

t <-- logger
deactivate logger

t -> i: moveToTecton(target)
activate i
note right: lásd: Insect.moveToTecton

t <-- i
deactivate i

t -> logger: print("void", "moveToTecton", target)
activate logger

t <-- logger
deactivate logger

t -> logger: printState(insect)
activate logger
t <-- logger
deactivate logger

opt ins.tecton != t1
	t -> logger: printError("test_moveToTecton4 failed")
	activate logger

	t <-- logger
	deactivate logger
end

deactivate t


@enduml