@startuml Insectologist.hasMoreActions

participant "ins: Insectologist" as ins
participant "i: Insect" as i

-> ins: hasMoreActions()
activate ins

loop for each insect

	ins -> i: getActions()
	activate i

	ins <-- i: actions
	deactivate i

	opt actions is not empty
		<-- ins: result = true
	end

end

<-- ins: result = false
deactivate ins

@enduml