@startuml Cut
title MushroomThread.cut

participant "i: Insect" as insect
participant "mt: MushroomThread" as mt
participant "from: Tecton" as from
participant "to: Tecton" as to


insect -> mt : cut()
activate insect
activate mt

mt -> from : removeConnection(mt)
activate from
from --> mt
deactivate from

mt -> to : removeConnection(mt)
activate to
to --> mt
deactivate to

insect <-- mt
deactivate mt
deactivate insect

@enduml