@startuml Cut
participant "mt: MushroomThread" as mt
participant "parnet: Mushroom" as parent
participant "from: Tecton" as from
participant "to: Tecton" as to


-> mt : cut()
activate mt

mt -> parent: removeThread(mt)
activate parent
parent --> mt 
deactivate parent

mt -> from : removeConnection(mt)
activate from
from --> mt
deactivate from

mt -> to : removeConnection(mt)
activate to
to --> mt
deactivate to

<-- mt
deactivate mt

@enduml