@startuml Get Conected Threads
participant "mb: MushroomBody" as mb
participant "mb.tecton: Tecton" as tecton
participant "mt: MushroomThread" as mt
collections "queue: Tecton" as q
collections "visited: Tecton" as visited
collections "result: MushroomThreads" as result

-> mb: getConnectedThreads()
mb -> tecton: getThreads(mb.parent)
tecton --> mb: threads: MushroomThreads[0..*]

    loop for each thread in threads 
        opt !queue.contains(thread.getTo()) && visited.get
            mb -> q: add(thread.getTo())
            q --> mb
        end
        opt !queue.contains(thread.getTo())
            mb -> q: add(thread.getTo())
        end
    end

    loop while queue is not empty

    end

@enduml