@startuml Grow Body Action
participant "gba: GrowBodyAction" as gba
participant "gba.mushroom: Mushroom" as m

-> gba: perform()
activate gba
gba -> m: growBody()
activate m
m --> gba
deactivate m
<-- gba
deactivate gba

@enduml