@startuml Insectologist.onEndOfTheRound

participant "ins: Insectologist" as ins
participant "i: Insect" as i

-> ins: onEndOfTheRound()
activate ins

loop for each insect

	ins -> i: onEndOfTheRound()
	activate i

	alt canMove
		i -> i: refreshActionPoints()
		activate i

		i --> i
		deactivate i
	else
		i -> i: setCanMove(true)
		activate i

		i --> i
		deactivate i
	end

	opt not canCut && actionPointsToWait == 0
		i -> i: setCanCut(true)
		activate i

		i --> i
		deactivate i
	end

	ins <-- i
	deactivate i

end

<-- ins
deactivate ins

@enduml