@startuml Insect.eatMushroomSpore

participant "i: Insect" as insect
participant "i.tecton: Tecton" as tecton
participant "s: MushroomSpore" as spore

-> insect: eatMushroomSpore()
activate insect

insect -> tecton: getRandomSpore()
deactivate insect
activate tecton

insect <-- tecton: s: MushroomSpore
deactivate tecton
activate insect

insect -> spore: applyEffect(i)
deactivate insect
activate spore

insect <-- spore
deactivate spore
activate insect

<-- insect
deactivate insect

@enduml