@startuml SporeEating
title Insect.eatMushroomSpore

actor "Inscetologist" as insectologist  
participant "insect: Insect" as insect
participant "spore: Spore" as spore
participant "effect: Effect" as effect

insectologist -> insect: eatMushroomSpore(spore)
activate insectologist
activate insect
    
insect->spore : applyEffect(insect)
activate spore

spore->spore : generateEffect()
activate spore
deactivate spore

spore ->effect : applyEffect(insect)
activate effect
note right: Effectek kifejtve külön diagramokon (Effect.applyEffect)

spore <-- effect
deactivate effect

insect <-- spore
deactivate spore

insectologist <-- insect
deactivate insect
deactivate insectologist

@enduml