@startuml SporeEating

participant "Insect" as insect
participant "Spore" as spore
participant "effect: Effect" as effect


->insect: eatMushroomSpore(Spore)
activate insect

    
insect->spore : applyEffect(insect)

activate spore



spore->spore : generateEffect()
activate spore

spore --> spore: effect
deactivate spore


spore ->effect : applyEffect(insect)
activate effect

spore <-- effect
deactivate effect

insect <-- spore
deactivate spore

<-- insect
deactivate insect



@enduml