@startuml Insect.getActions

participant "i: Insect" as insect
participant "i.tecton: Tecton" as tecton
participant "MoveInsectAction" as mi_action
participant "CutThreadAction" as ct_action
participant "EatSporeAction" as es_action

-> insect: Insect.getActions()
activate insect

insect -> tecton: getThreads()
deactivate insect
activate tecton

insect <-- tecton: MushroomThread[]
deactivate tecton
activate insect

loop for each thread

	insect -> mi_action: Instantiate(i, thread)
	deactivate insect
	activate mi_action

	insect <-- mi_action: moveInsectActionResult
	deactivate mi_action
	activate insect

	insect -> ct_action: Instantiate(i, thread)
	deactivate insect
	activate ct_action

	insect <-- ct_action: cutThreadActionResult
	deactivate ct_action
	activate insect

	insect -> insect: result += moveInsectActionResult + cutThreadActionResult

end

insect -> tecton: getSpores()
deactivate insect
activate tecton

insect <-- tecton: spores
deactivate tecton
activate insect

opt spores is not empty
	insect -> es_action: Instantiate(i)
	deactivate insect
	activate es_action

	insect <-- es_action: eatSporeAction
	deactivate es_action
	activate insect

	insect -> insect: result += eatSporeAction
end

<-- insect: result: Action[]
deactivate insect

@enduml