@startuml Insect
title Insect

actor "Insectologist" as insectologist
participant "i: Insect" as insect
participant "i.tecton: Tecton" as t1
participant "to: Tecton" as t2

insectologist -> insect: moveToTecton(to)
activate insectologist
activate insect

insect -> t1: hasThreadTo(to)
activate t1

t1 --> insect: bool
deactivate t1

opt van fonál a két tekton között
	insect -> t1: unregisterInsect(i)
	activate t1

	t1 --> insect
	deactivate t1

	insect -> t2: registerInsect(i)
	activate t2

	t2 --> insect
	deactivate t2

	'insect -> insect: i.tecton = to
end

insectologist <-- insect
deactivate insect
deactivate insectologist

@enduml