@startuml Insect.eatMeatMushroomSpore

participant "SpeedEffect" as effect

participant "Insect" as insect




-> effect : applyEffect(Insect)
activate effect

effect->insect:setRemainingActionPoints()
activate insect

effect<--insect
deactivate insect

<--effect
deactivate effect



@enduml