@startuml tectonGrowThreadTest

title SingleThreadTecton Grow Thread Success

actor "Tester" as tst
participant "s: Skeleton" as s
participant "t2: SingleThreadTecton" as t2
participant "newMt: MushroomThread" as newMt

activate tst

tst -> s: SingleThreadTectonGrowThreadSuccess()
activate s

s -> newMt: Instantiate()
activate newMt
s <-- newMt
deactivate newMt

s -> t2: addConnection(newMt)
activate t2

t2 -> t2: mushroomThreads.add(newMt)

s <-- t2
deactivate t2

tst <-- s
deactivate s

deactivate tst

@enduml