@startuml tectonSplitTest

title Tecton Split

actor "Tester" as tst
participant "s: Skeleton" as s
participant "t: Tecton" as t
participant "newTec: Tecton" as ntec

activate tst

tst -> s: TectonSplit()
activate s

s -> t: split()
activate t

' ez nemtom így mennyire jó, de nincs jobb ötletem és leszarom XD
t -> ntec: Instantiate([t, t.getNeighbours()])
activate ntec

ntec -> ntec: neighbours.add(t)

loop nt in t.getNeighbours()

ntec -> ntec: neighbours.add(nt)

end

t <-- ntec:
deactivate ntec

t -> t: neighbours.add(newTec)

s <-- t:
deactivate t

tst <-- s
deactivate s

deactivate tst

@enduml