@startuml BlockEffect

participant "BlockEffect" as effect
participant "Insect" as insect

-> effect : applyEffect(Insect)
activate effect

effect->insect:setActionPointsToWait()
activate insect

effect<--insect

effect->insect:setCanCut(false)
effect<--insect
deactivate insect

<--effect
deactivate effect

@enduml