@startuml SlowEffect

participant "SlowEffect" as effect

participant "Insect" as insect




-> effect : applyEffect(Insect)
activate effect

effect->insect: subActionPoints()
activate insect

effect<--insect
deactivate insect

<--effect
deactivate effect




@enduml