@startuml SlowEffect
title SlowEffect.applyEffect

participant "spore: MushroomSpore" as spore
participant "se: SlowEffect" as effect
participant "i: Insect" as insect


spore -> effect : applyEffect(i)
note left: eatMushroomSpore hívja meg
activate spore
activate effect

effect->insect: exhaustActions()
activate insect

effect<--insect
deactivate insect

spore <--effect
deactivate effect
deactivate spore



@enduml