@startuml SpeedEffect
title SpeedEffect.applyEffect

participant "spore: MushroomSpore" as spore
participant "se: SpeedEffect" as effect
participant "i: Insect" as insect

spore -> effect : applyEffect(i)
activate spore
activate effect

effect->insect: addActionPoints()
activate insect

effect<--insect
deactivate insect

spore <--effect
deactivate effect
deactivate spore

@enduml