@startuml StunEffect
title StunEffect.applyEffect

participant "spore: MushroomSpore" as spore
participant "se: StunEffect" as effect
participant "i: Insect" as insect

spore -> effect : applyEffect(i)
activate spore
activate effect

effect->insect:subActionPoints()
activate insect

effect<--insect

effect->insect:setCanMove()
effect<--insect
deactivate insect

spore <--effect
deactivate effect
deactivate spore



@enduml