@startuml StunEffect

participant "StunEffect" as effect

participant "Insect" as insect




-> effect : applyEffect(Insect)
activate effect

effect->insect:subActionPoints()
activate insect

effect<--insect

effect->insect:setCanMove(false)
effect<--insect
deactivate insect

<--effect
deactivate effect




@enduml