' Test-casek amikhez jó ez a diagram:
' - KeepAliveTecton Keep Alive

@startuml communicationTecton6

title KeepAliveTecton Keep Alive

actor "Tester" as ts
participant "t: KeepAliveTecton" as t
participant "mt1: MushroomThread" as mt1

' inicializálások

activate ts

ts -> t: 1.1 -> Initialize()
activate t
ts <-- t
deactivate t

ts -> mt1: 1.3 -> Initialize(t)
activate mt1
mt1 -> t: 1.3.1 <- addConnection(mt1)
activate t
mt1 <-- t
deactivate t
ts <-- mt1
deactivate mt1

deactivate ts

@enduml