@startuml Cut
title MushroomThread.cut

participant "mt: MushroomThread" as mt

-> mt : cut()
note right: hívó fél: Insect.cutMushroomThread\nvagy Tecton.split
activate mt

mt -> mt: cutState = CutState.CUT
activate mt
mt --> mt
deactivate mt

<-- mt
deactivate mt

@enduml