@startuml GetConectedThreads
participant "body: MushroomBody" as body
participant "parent: Mushroom" as parent
participant "thread: MushroomThread" as thread
collections "connectedThreads: MushroomThread[0..*]" as connectedThreads

-> body : getConnnectedThreads()
activate body

body -> parent : getThreads()
activate parent
parent --> body : threads: MushroomThread[0..*]
deactivate parent

body -> connectedThreads : instantiate
activate connectedThreads

    loop for each thread in threads
        body -> thread: getConnections()

        activate thread
        thread --> body : connections: MushroomThread[0..*]
        deactivate thread

        loop for each connection in connections
            opt connectedThreads does not have connection
                body -> connectedThreads : add(connection)
                connectedThreads --> body
                deactivate connectedThreads
            end

        end
    end

<-- body : connectedThreads
deactivate body

@enduml