@startuml Effects Init

title BlockEffect

actor "Tester" as tester
participant "blockEffect: BlockEffect" as block
participant "t: Tecton" as t
participant "i: Insect" as i

activate tester

	tester -> t: Initialize()
	activate t
	t --> tester
	deactivate t

	tester -> i: Initialize(t)
	activate i

		i-> t: registerInsect(i)
		activate t
		t --> i
		deactivate t

	tester <-- i
	deactivate i

	tester -> block: Initialize()
	activate block
	block --> tester

	tester->block: applyEffect(i)
	block-->tester
	deactivate block

deactivate tester

@enduml