@startuml Effects Init

title Effects Init

actor "Tester" as tester

participant "speedEffect: SpeedEffect" as speed
participant "blockEffect: BlockEffect" as block
participant "slowEffect: SlowEffect" as slow

participant "t: Tecton" as t

participant "i1: Insect" as i1
participant "i2: Insect" as i2
participant "i3: Insect" as i3

activate tester

tester -> t: Initialize()
activate t
t --> tester
deactivate t

tester -> i1: Initialize(t)
activate i1
i1 -> t: registerInsect(i1)
activate t
t --> i1
deactivate t
i1 --> tester
deactivate i1

tester -> i2: Initialize(t)
activate i2
i2 -> t: registerInsect(i2)
activate t
t --> i2
deactivate t
i2 --> tester
deactivate i2

tester -> i3: Initialize(t)
activate i3
i3 -> t: registerInsect(i3)
activate t
t --> i3
deactivate t
i3 --> tester
deactivate i3

tester -> speed: Initialize()
activate speed
speed --> tester
deactivate speed

tester -> block: Initialize()
activate block
block --> tester
deactivate block

tester -> slow: Initialize()
activate slow
slow --> tester
deactivate slow

@enduml