@startuml Effects Init

title StunEffects 

actor "Tester" as test

participant "Skeleton" as tester
activate test
test ->tester:testEffect3()

participant "stunEffect: StunEffect" as speed


participant "t: Tecton" as t

participant "i1: Insect" as i


activate tester

tester -> t: Initialize()
activate t
t --> tester
deactivate t

tester -> i: Initialize(t)
activate i
i-> t: registerInsect(i)
activate t
t --> i
deactivate t
i --> tester
deactivate i






tester -> speed: Initialize()
activate speed
speed --> tester

tester->speed: applyEffect(i)
speed-->tester
deactivate speed

test <-- tester




@enduml